# Generated by Django 3.2.3 on 2021-05-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('buy_price', models.CharField(max_length=30)),
                ('desired_price_fall', models.CharField(max_length=30)),
                ('desired_sell_price', models.TextField()),
            ],
        ),
    ]
