# Generated by Django 3.2.3 on 2021-05-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morda', '0002_alter_coin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='last_prices',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='desired_sell_price',
            field=models.CharField(max_length=30),
        ),
    ]
