# Generated by Django 3.2.3 on 2021-05-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morda', '0003_auto_20210516_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
