# Generated by Django 3.2.3 on 2021-05-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morda', '0006_alter_coin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='id',
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False),
        ),
    ]
